name = "Shoka"
license = "MIT"
licenselink = "https://github.com/amehime/hexo-theme-shoka/blob/master/LICENSE"
description = "Hugo port of Hexo Theme Shoka"
homepage = "https://github.com/amehime/hexo-theme-shoka"
tags = ["blog", "responsive", "theme", "shoka"]
features = ["pjax", "search", "comments", "dark-mode"]
min_version = "0.118.0"

[author]
  name = "Ruri Shimotsuki"
  homepage = "https://shoka.lostyu.me"
